# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        kaggle: 1
        resnet: 1
        autonomous: 3
        vision transformer: 3
        semantic: 3
        semantic segmentation: 3
        object detection: 3
        transformer: 3 

# 通知の閾値
score_threshold: 0
